# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe795058cd8cf554b2b7af8d2558beebdc03268adc2258d0f3099f350140a546cf28a69d64723481ec65cf6fc85d780873553d42d542e49d5a6f5a3f4666ff92

test:
  secret_key_base: 03e007cff6223279d9bae39e9ffaf242e803e7c6a28f6d49210a070a872b8193925939611f3462af5421fd4434d43b3a7563cad462e42f7e4423d0d5c690da82

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
